# Generated by Django 5.1.6 on 2025-02-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmodel",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
